export const AssetManifest = {
  maps: {
    livingroom: {
      mapKey: "map_livingroom",
      mapJson: "/assets/maps/livingroom/map.json",
      groundKey: "ground_livingroom",
      groundImage: "/assets/maps/livingroom/客厅.png",
      tilesetKey: "tileset_livingroom",
      tilesetImage: "/assets/maps/livingroom/tileset.png",
      furnitureImages: [
        { key: "item_01", path: "/assets/maps/livingroom/客厅物品_sprites/item_01.png" },
        { key: "item_02", path: "/assets/maps/livingroom/客厅物品_sprites/item_02.png" },
        { key: "item_03", path: "/assets/maps/livingroom/客厅物品_sprites/item_03.png" },
        { key: "item_04", path: "/assets/maps/livingroom/客厅物品_sprites/item_04.png" },
        { key: "item_05", path: "/assets/maps/livingroom/客厅物品_sprites/item_05.png" },
        { key: "item_06", path: "/assets/maps/livingroom/客厅物品_sprites/item_06.png" },
        { key: "item_06_flip", path: "/assets/maps/livingroom/客厅物品_sprites/item_06_flip.png" },
        { key: "item_07", path: "/assets/maps/livingroom/客厅物品_sprites/item_07.png" },
        { key: "item_08", path: "/assets/maps/livingroom/客厅物品_sprites/item_08.png" },
        { key: "item_09", path: "/assets/maps/livingroom/客厅物品_sprites/item_09.png" },
        { key: "item_10", path: "/assets/maps/livingroom/客厅物品_sprites/item_10.png" },
        { key: "item_11", path: "/assets/maps/livingroom/客厅物品_sprites/item_11.png" },
        { key: "item_12", path: "/assets/maps/livingroom/客厅物品_sprites/item_12.png" },
        { key: "item_13", path: "/assets/maps/livingroom/客厅物品_sprites/item_13.png" },
        { key: "item_14", path: "/assets/maps/livingroom/客厅物品_sprites/item_14.png" },
        { key: "item_15", path: "/assets/maps/livingroom/客厅物品_sprites/item_15.png" },
      ],
    },
    bathroom: {
      mapKey: "map_bathroom",
      mapJson: "/assets/maps/bathroom/map.json",
      groundKey: "ground_bathroom",
      groundImage: "/assets/maps/bathroom/卫生间.png",
      tilesetKey: "tileset_bathroom",
      tilesetImage: "/assets/maps/bathroom/tileset.png",
    },
    bedroom: {
      mapKey: "map_bedroom",
      mapJson: "/assets/maps/bedroom/map.json",
      groundKey: "ground_bedroom",
      groundImage: "/assets/maps/bedroom/主角房间.png",
      tilesetKey: "tileset_bedroom",
      tilesetImage: "/assets/maps/bedroom/tileset.png",
    },
    bedroom_parents: {
      mapKey: "map_bedroom_parents",
      mapJson: "/assets/maps/bedroom_parents/map.json",
      groundKey: "ground_bedroom_parents",
      groundImage: "/assets/maps/bedroom_parents/父母房间.png",
      tilesetKey: "tileset_bedroom_parents",
      tilesetImage: "/assets/maps/bedroom_parents/tileset.png",
    },
    kitchen: {
      mapKey: "map_kitchen",
      mapJson: "/assets/maps/kitchen/map.json",
      groundKey: "ground_kitchen",
      groundImage: "/assets/maps/kitchen/厨房.png",
      tilesetKey: "tileset_kitchen",
      tilesetImage: "/assets/maps/kitchen/tileset.png",
    },
    dormitory: {
      mapKey: "map_dormitory",
      mapJson: "/assets/maps/dormitory/map.json",
      groundKey: "ground_dormitory",
      groundImage: "/assets/maps/dormitory/sleep.png",
      tilesetKey: "tileset_dormitory",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
      furnitureImages: [
        { key: "dorm_item_01", path: "/assets/maps/dormitory/物品_sprites/item_01.png" },
        { key: "dorm_item_02", path: "/assets/maps/dormitory/物品_sprites/item_02.png" },
        { key: "dorm_item_03", path: "/assets/maps/dormitory/物品_sprites/item_03.png" },
        { key: "dorm_item_04", path: "/assets/maps/dormitory/物品_sprites/item_04.png" },
        { key: "dorm_item_05", path: "/assets/maps/dormitory/物品_sprites/item_05.png" },
        { key: "dorm_item_06", path: "/assets/maps/dormitory/物品_sprites/item_06.png" },
        { key: "dorm_item_07", path: "/assets/maps/dormitory/物品_sprites/item_07.png" },
        { key: "dorm_item_08", path: "/assets/maps/dormitory/物品_sprites/item_08.png" },
        { key: "dorm_item_09", path: "/assets/maps/dormitory/物品_sprites/item_09.png" },
        { key: "dorm_item_10", path: "/assets/maps/dormitory/物品_sprites/item_10.png" },
        { key: "dorm_item_11", path: "/assets/maps/dormitory/物品_sprites/item_11.png" },
        { key: "dorm_item_12", path: "/assets/maps/dormitory/物品_sprites/item_12.png" },
        { key: "dorm_item_13", path: "/assets/maps/dormitory/物品_sprites/item_13.png" },
        { key: "dorm_item_14", path: "/assets/maps/dormitory/物品_sprites/item_14.png" },
        { key: "dorm_item_15", path: "/assets/maps/dormitory/物品_sprites/item_15.png" },
        { key: "dorm_item_16", path: "/assets/maps/dormitory/物品_sprites/item_16.png" },
        { key: "dorm_item_17", path: "/assets/maps/dormitory/物品_sprites/item_17.png" },
        { key: "dorm_item_18", path: "/assets/maps/dormitory/物品_sprites/item_18.png" },
        { key: "dorm_item_19", path: "/assets/maps/dormitory/物品_sprites/item_19.png" },
        { key: "dorm_item_20", path: "/assets/maps/dormitory/物品_sprites/item_20.png" },
        { key: "dorm_item_21", path: "/assets/maps/dormitory/物品_sprites/item_21.png" },
        { key: "dorm_item_22", path: "/assets/maps/dormitory/物品_sprites/item_22.png" },
        { key: "dorm_item_23", path: "/assets/maps/dormitory/物品_sprites/item_23.png" },
        { key: "dorm_item_24", path: "/assets/maps/dormitory/物品_sprites/item_24.png" },
      ],
    },
    balcony: {
      mapKey: "map_balcony",
      mapJson: "/assets/maps/balcony/map.json",
      groundKey: "ground_balcony",
      groundImage: "/assets/maps/balcony/阳台_白天.png",
      tilesetKey: "tileset_balcony",
      tilesetImage: "/assets/maps/balcony/tileset.png",
      furnitureImages: [
        { key: "item_01", path: "/assets/maps/balcony/物品_sprites/item_01.png" },
        { key: "item_02", path: "/assets/maps/balcony/物品_sprites/item_02.png" },
        { key: "item_03", path: "/assets/maps/balcony/物品_sprites/item_03.png" },
        { key: "item_04", path: "/assets/maps/balcony/物品_sprites/item_04.png" },
        { key: "item_05", path: "/assets/maps/balcony/物品_sprites/item_05.png" },
        { key: "item_06", path: "/assets/maps/balcony/物品_sprites/item_06.png" },
        { key: "item_07", path: "/assets/maps/balcony/物品_sprites/item_07.png" },
        { key: "item_08", path: "/assets/maps/balcony/物品_sprites/item_08.png" },
        { key: "item_09", path: "/assets/maps/balcony/物品_sprites/item_09.png" },
      ],
    },
    /** 阳台夜间测试版（含多边形遮挡） */
    balcony_night: {
      mapKey: "map_balcony_night",
      mapJson: "/assets/maps/balcony/map.json",
      groundKey: "ground_balcony_night",
      groundImage: "/assets/maps/balcony/阳台_夜晚.png",
      tilesetKey: "tileset_balcony_night",
      tilesetImage: "/assets/maps/balcony/tileset.png",
    },
    /** 宿舍白天版（使用 map1.json + 白天底图，用于第三幕） */
    dormitory_day: {
      mapKey: "map_dormitory_day",
      mapJson: "/assets/maps/dormitory/map1.json",
      groundKey: "ground_dormitory_day",
      groundImage: "/assets/maps/dormitory/宿舍.png",
      tilesetKey: "tileset_dormitory_day",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    /** 宿舍第四幕（使用 map2.json + 夜晚电脑关底图） */
    dormitory_act4: {
      mapKey: "map_dorm_act4",
      mapJson: "/assets/maps/dormitory/map2.json",
      groundKey: "ground_dorm_act4",
      groundImage: "/assets/maps/dormitory/宿舍_夜晚_电脑关.png",
      tilesetKey: "tileset_dorm_act4",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
  },
  /** 玩家帧动画素材（yps = 叶平生，主角） */
  frames: {
    yps: {
      basePath: "assets/sprites/frames/yps_frames",
      // 跑步方向（每个方向6帧）
      run: ["left", "right", "front", "back"],
      // 单帧方向（坐下/站立各方向）
      sit: ["sit_left", "sit_right", "sit_front", "sit_back"],
      stand: ["stand_left", "stand_right", "stand_front", "stand_back"],
    },
    ly: {
      basePath: "assets/sprites/frames/ly_frames",
      run: ["left", "right", "front", "back"],
      sit: ["sit_left", "sit_right", "sit_front", "sit_back"],
      stand: ["stand_left", "stand_right", "stand_front", "stand_back"],
    },
  },
} as const;
