const CLASSROOM_MAP_VERSION = "20260711_spawn255";

export const AssetManifest = {
  maps: {
    livingroom: {
      mapKey: "map_livingroom",
      mapJson: "/assets/maps/livingroom/map.json",
      groundKey: "ground_livingroom",
      groundImage: "/assets/maps/livingroom/客厅.png",
      tilesetKey: "tileset_livingroom",
      tilesetImage: "/assets/maps/livingroom/tileset.png",
      furnitureImages: [
        { key: "item_01", path: "/assets/maps/livingroom/客厅物品_sprites/item_01.png" },
        { key: "item_02", path: "/assets/maps/livingroom/客厅物品_sprites/item_02.png" },
        { key: "item_03", path: "/assets/maps/livingroom/客厅物品_sprites/item_03.png" },
        { key: "item_04", path: "/assets/maps/livingroom/客厅物品_sprites/item_04.png" },
        { key: "item_05", path: "/assets/maps/livingroom/客厅物品_sprites/item_05.png" },
        { key: "item_06", path: "/assets/maps/livingroom/客厅物品_sprites/item_06.png" },
        { key: "item_06_flip", path: "/assets/maps/livingroom/客厅物品_sprites/item_06_flip.png" },
        { key: "item_07", path: "/assets/maps/livingroom/客厅物品_sprites/item_07.png" },
        { key: "item_08", path: "/assets/maps/livingroom/客厅物品_sprites/item_08.png" },
        { key: "item_09", path: "/assets/maps/livingroom/客厅物品_sprites/item_09.png" },
        { key: "item_10", path: "/assets/maps/livingroom/客厅物品_sprites/item_10.png" },
        { key: "item_11", path: "/assets/maps/livingroom/客厅物品_sprites/item_11.png" },
        { key: "item_12", path: "/assets/maps/livingroom/客厅物品_sprites/item_12.png" },
        { key: "item_13", path: "/assets/maps/livingroom/客厅物品_sprites/item_13.png" },
        { key: "item_14", path: "/assets/maps/livingroom/客厅物品_sprites/item_14.png" },
        { key: "item_15", path: "/assets/maps/livingroom/客厅物品_sprites/item_15.png" },
      ],
    },
    bathroom: {
      mapKey: "map_bathroom",
      mapJson: "/assets/maps/bathroom/map.json",
      groundKey: "ground_bathroom",
      groundImage: "/assets/maps/bathroom/卫生间.png",
      tilesetKey: "tileset_bathroom",
      tilesetImage: "/assets/maps/bathroom/tileset.png",
    },
    bedroom: {
      mapKey: "map_bedroom",
      mapJson: "/assets/maps/bedroom/map.json",
      groundKey: "ground_bedroom",
      groundImage: "/assets/maps/bedroom/主角房间.png",
      tilesetKey: "tileset_bedroom",
      tilesetImage: "/assets/maps/bedroom/tileset.png",
    },
    bedroom_luggage: {
      mapKey: "map_bedroom_luggage",
      mapJson: "/assets/maps/bedroom/new_map.json",
      groundKey: "ground_bedroom_luggage",
      groundImage: "/assets/maps/bedroom/主角房间(带行李).png",
      tilesetKey: "tileset_bedroom_luggage",
      tilesetImage: "/assets/maps/bedroom/tileset.png",
    },
    bedroom_parents: {
      mapKey: "map_bedroom_parents",
      mapJson: "/assets/maps/bedroom_parents/map.json",
      groundKey: "ground_bedroom_parents",
      groundImage: "/assets/maps/bedroom_parents/父母房间.png",
      tilesetKey: "tileset_bedroom_parents",
      tilesetImage: "/assets/maps/bedroom_parents/tileset.png",
    },
    kitchen: {
      mapKey: "map_kitchen",
      mapJson: "/assets/maps/kitchen/map.json",
      groundKey: "ground_kitchen",
      groundImage: "/assets/maps/kitchen/厨房.png",
      tilesetKey: "tileset_kitchen",
      tilesetImage: "/assets/maps/kitchen/tileset.png",
    },
    /** 厨房用品店（校外店铺，厨具便利店） */
    shop: {
      mapKey: "map_shop",
      mapJson: "/assets/maps/shop/map.json",
      groundKey: "ground_shop",
      groundImage: "/assets/maps/shop/厨具便利店.png",
      tilesetKey: "tileset_shop",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    dormitory: {
      mapKey: "map_dormitory",
      mapJson: "/assets/maps/dormitory/map.json",
      groundKey: "ground_dormitory",
      groundImage: "/assets/maps/dormitory/sleep.png",
      tilesetKey: "tileset_dormitory",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
      furnitureImages: [
        { key: "dorm_item_01", path: "/assets/maps/dormitory/物品_sprites/item_01.png" },
        { key: "dorm_item_02", path: "/assets/maps/dormitory/物品_sprites/item_02.png" },
        { key: "dorm_item_03", path: "/assets/maps/dormitory/物品_sprites/item_03.png" },
        { key: "dorm_item_04", path: "/assets/maps/dormitory/物品_sprites/item_04.png" },
        { key: "dorm_item_05", path: "/assets/maps/dormitory/物品_sprites/item_05.png" },
        { key: "dorm_item_06", path: "/assets/maps/dormitory/物品_sprites/item_06.png" },
        { key: "dorm_item_07", path: "/assets/maps/dormitory/物品_sprites/item_07.png" },
        { key: "dorm_item_08", path: "/assets/maps/dormitory/物品_sprites/item_08.png" },
        { key: "dorm_item_09", path: "/assets/maps/dormitory/物品_sprites/item_09.png" },
        { key: "dorm_item_10", path: "/assets/maps/dormitory/物品_sprites/item_10.png" },
        { key: "dorm_item_11", path: "/assets/maps/dormitory/物品_sprites/item_11.png" },
        { key: "dorm_item_12", path: "/assets/maps/dormitory/物品_sprites/item_12.png" },
        { key: "dorm_item_13", path: "/assets/maps/dormitory/物品_sprites/item_13.png" },
        { key: "dorm_item_14", path: "/assets/maps/dormitory/物品_sprites/item_14.png" },
        { key: "dorm_item_15", path: "/assets/maps/dormitory/物品_sprites/item_15.png" },
        { key: "dorm_item_16", path: "/assets/maps/dormitory/物品_sprites/item_16.png" },
        { key: "dorm_item_17", path: "/assets/maps/dormitory/物品_sprites/item_17.png" },
        { key: "dorm_item_18", path: "/assets/maps/dormitory/物品_sprites/item_18.png" },
        { key: "dorm_item_19", path: "/assets/maps/dormitory/物品_sprites/item_19.png" },
        { key: "dorm_item_20", path: "/assets/maps/dormitory/物品_sprites/item_20.png" },
        { key: "dorm_item_21", path: "/assets/maps/dormitory/物品_sprites/item_21.png" },
        { key: "dorm_item_22", path: "/assets/maps/dormitory/物品_sprites/item_22.png" },
        { key: "dorm_item_23", path: "/assets/maps/dormitory/物品_sprites/item_23.png" },
        { key: "dorm_item_24", path: "/assets/maps/dormitory/物品_sprites/item_24.png" },
      ],
    },
    balcony: {
      mapKey: "map_balcony",
      mapJson: "/assets/maps/balcony/map.json",
      groundKey: "ground_balcony",
      groundImage: "/assets/maps/balcony/阳台_白天.png",
      tilesetKey: "tileset_balcony",
      tilesetImage: "/assets/maps/balcony/tileset.png",
      furnitureImages: [
        { key: "item_01", path: "/assets/maps/balcony/物品_sprites/item_01.png" },
        { key: "item_02", path: "/assets/maps/balcony/物品_sprites/item_02.png" },
        { key: "item_03", path: "/assets/maps/balcony/物品_sprites/item_03.png" },
        { key: "item_04", path: "/assets/maps/balcony/物品_sprites/item_04.png" },
        { key: "item_05", path: "/assets/maps/balcony/物品_sprites/item_05.png" },
        { key: "item_06", path: "/assets/maps/balcony/物品_sprites/item_06.png" },
        { key: "item_07", path: "/assets/maps/balcony/物品_sprites/item_07.png" },
        { key: "item_08", path: "/assets/maps/balcony/物品_sprites/item_08.png" },
        { key: "item_09", path: "/assets/maps/balcony/物品_sprites/item_09.png" },
      ],
    },
    /** 阳台夜间测试版（含多边形遮挡） */
    balcony_night: {
      mapKey: "map_balcony_night",
      mapJson: "/assets/maps/balcony/map.json",
      groundKey: "ground_balcony_night",
      groundImage: "/assets/maps/balcony/阳台_夜晚.png",
      tilesetKey: "tileset_balcony_night",
      tilesetImage: "/assets/maps/balcony/tileset.png",
    },
    /** 宿舍白天版（使用 map1.json + 白天底图，用于第三幕） */
    dormitory_day: {
      mapKey: "map_dormitory_day",
      mapJson: "/assets/maps/dormitory/map1.json",
      groundKey: "ground_dormitory_day",
      groundImage: "/assets/maps/dormitory/宿舍.png",
      tilesetKey: "tileset_dormitory_day",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    /** 宿舍第四幕（使用 map2.json + 夜晚电脑关底图） */
    dormitory_act4: {
      mapKey: "map_dorm_act4",
      mapJson: "/assets/maps/dormitory/map2.json",
      groundKey: "ground_dorm_act4",
      groundImage: "/assets/maps/dormitory/宿舍_夜晚_电脑关.png",
      tilesetKey: "tileset_dorm_act4",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    /** 校园小卖部（第七部分 · 赛前准备） */
    shop_school: {
      mapKey: "map_shop_school",
      mapJson: "/assets/maps/shop_school/map.json",
      groundKey: "ground_shop_school",
      groundImage: "/assets/maps/shop_school/便利店.png",
      tilesetKey: "tileset_shop_school",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    classroom: {
      mapKey: `map_classroom_${CLASSROOM_MAP_VERSION}`,
      mapJson: `/assets/maps/classroom/map.json?v=${CLASSROOM_MAP_VERSION}`,
      groundKey: "ground_classroom",
      groundImage: "/assets/maps/classroom/教室.png",
      tilesetKey: "tileset_classroom",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    classroom_3: {
      mapKey: "map_classroom_3",
      mapJson: "/assets/maps/classroom_3/map.json",
      groundKey: "ground_classroom_3",
      groundImage: "/assets/maps/classroom_3/教室.png",
      tilesetKey: "tileset_classroom_3",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    corridor: {
      mapKey: "map_corridor",
      mapJson: "/assets/maps/corridor/map.json",
      groundKey: "ground_corridor",
      groundImage: "/assets/maps/corridor/走廊.png",
      tilesetKey: "tileset_corridor",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    gate: {
      mapKey: "map_gate",
      mapJson: "/assets/maps/gate/map.json",
      groundKey: "ground_gate",
      groundImage: "/assets/maps/gate/校门白天.png",
      tilesetKey: "tileset_gate",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    gate_night: {
      mapKey: "map_gate_night",
      mapJson: "/assets/maps/gate/map.json",
      groundKey: "ground_gate_night",
      groundImage: "/assets/maps/gate/校门夜晚.png",
      tilesetKey: "tileset_gate_night",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    rooftop: {
      mapKey: "map_rooftop",
      mapJson: "/assets/maps/rooftop/map.json",
      groundKey: "ground_rooftop",
      groundImage: "/assets/maps/rooftop/天台.png",
      tilesetKey: "tileset_rooftop",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    teacher_office: {
      mapKey: "map_teacher_office",
      mapJson: "/assets/maps/teacher_office/map.json",
      groundKey: "ground_teacher_office",
      groundImage: "/assets/maps/teacher_office/教师办公室.png",
      tilesetKey: "tileset_teacher_office",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    waiting: {
      mapKey: "map_waiting",
      mapJson: "/assets/maps/waiting/map.json",
      groundKey: "ground_waiting",
      groundImage: "/assets/maps/waiting/进入界面.png",
      tilesetKey: "tileset_waiting",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
    wang_gallery: {
      mapKey: "map_wang_gallery",
      mapJson: "/assets/maps/wang_gallery/map.json",
      groundKey: "ground_wang_gallery",
      groundImage: "/assets/maps/wang_gallery/美术教室.png",
      tilesetKey: "tileset_wang_gallery",
      tilesetImage: "/assets/maps/dormitory/tileset.png",
    },
  },
  /** 角色帧素材。按磁盘上真实存在的动作目录声明，避免请求不存在的帧。 */
  frames: [
    { key: "yps_frames", run: true, sit: true, stand: true },
    { key: "ly_frames", run: true, sit: true, stand: true, displayScaleMultiplier: 4 },
    { key: "cyh_frames", run: true, stand: true },
    {
      key: "dad_frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_023.png", stand_right: "frame_022.png",
        sit_front: "frame_025.png", sit_back: "frame_031.png", sit_left: "frame_030.png", sit_right: "frame_028.png",
      },
    },
    {
      key: "mom_frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_022.png", stand_right: "frame_022.png",
        sit_front: "frame_024.png", sit_back: "frame_029.png", sit_left: "frame_025.png", sit_right: "frame_025.png",
      },
    },
    {
      key: "npc_female1_frames",
      run: true,
      sit: true,
      stand: true,
      displayScaleMultiplier: 4,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      directoryOverrides: { stand_left: "npc_female1_frames_stand_right" },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_022.png", stand_right: "frame_022.png",
        sit_front: "frame_024.png", sit_back: "frame_027.png", sit_left: "frame_026.png", sit_right: "frame_026.png",
      },
    },
    {
      key: "npc_male_frames",
      folderPrefix: "npc_male _frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_023.png", stand_right: "frame_022.png",
        sit_front: "frame_010.png", sit_back: "frame_028.png", sit_left: "frame_019.png", sit_right: "frame_022.png",
      },
    },
    { key: "roommateA_frames", run: true, stand: true },
    {
      key: "roommateB_frames",
      run: true,
      stand: true,
      directoryOverrides: { stand_back: "roommateB2_frames_stand_back" },
    },
    { key: "shop_assistant_female_frames", stand: true },
    { key: "shop_assistant_male_frames", stand: true },
    {
      key: "teacher_frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_023.png", stand_right: "frame_022.png",
        sit_front: "frame_026.png", sit_back: "frame_031.png", sit_left: "frame_029.png", sit_right: "frame_029.png",
      },
    },
    {
      key: "teacher_monster_frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_022.png", stand_right: "frame_023.png",
        sit_front: "frame_024.png", sit_back: "frame_027.png", sit_left: "frame_026.png", sit_right: "frame_026.png",
      },
    },
    {
      key: "wql_frames",
      run: true,
      sit: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_023.png", stand_right: "frame_022.png",
        sit_front: "frame_030.png", sit_back: "frame_028.png", sit_left: "frame_026.png", sit_right: "frame_029.png",
      },
    },
    {
      key: "zjx_frames",
      run: true,
      sit: true,
      stand: true,
      displayScaleMultiplier: 4,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_006.png", stand_back: "frame_022.png", stand_left: "frame_014.png", stand_right: "frame_014.png",
        sit_front: "frame_007.png", sit_back: "frame_023.png", sit_left: "frame_015.png", sit_right: "frame_015.png",
      },
    },
    {
      key: "zqr_frames",
      run: true,
      sit: true,
      stand: true,
      displayScaleMultiplier: 4,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png", stand_back: "frame_015.png", stand_left: "frame_023.png", stand_right: "frame_023.png",
        sit_front: "frame_024.png", sit_back: "frame_025.png", sit_left: "frame_026.png", sit_right: "frame_026.png",
      },
    },
    {
      key: "lzx_frames",
      run: true,
      stand: true,
      displayScaleMultiplier: 4,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_006.png",
        stand_back: "frame_022.png",
        stand_left: "frame_014.png",
        stand_right: "frame_014.png",
      },
    },
    {
      key: "delinquent teenagers_frames",
      run: true,
      stand: true,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png",
        stand_back: "frame_015.png",
        stand_left: "frame_022.png",
        stand_right: "frame_022.png",
      },
    },
    {
      key: "？？？_frames",
      run: true,
      stand: true,
      displayScaleMultiplier: 4,
      runFrameStartOverrides: { left: 8, right: 8, front: 0, back: 16 },
      frameFileOverrides: {
        stand_front: "frame_014.png",
        stand_back: "frame_015.png",
        stand_left: "frame_022.png",
        stand_right: "frame_022.png",
      },
    },
  ],
} as const;
