import type { MapEntry } from "../types/gameMap";

export const MapRegistry: Record<string, MapEntry> = {
  livingroom: {
    mapKey: "map_livingroom",
    mapJson: "/assets/maps/livingroom/map.json",
    groundKey: "ground_livingroom",
    groundImage: "/assets/maps/livingroom/客厅.png",
    defaultSpawn: "spawn_livingroom_center",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/livingroom/客厅物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/livingroom/客厅物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/livingroom/客厅物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/livingroom/客厅物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/livingroom/客厅物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/livingroom/客厅物品_sprites/item_06.png" },
      { key: "item_06_flip", path: "/assets/maps/livingroom/客厅物品_sprites/item_06_flip.png" },
      { key: "item_07", path: "/assets/maps/livingroom/客厅物品_sprites/item_07.png" },
      { key: "item_08", path: "/assets/maps/livingroom/客厅物品_sprites/item_08.png" },
      { key: "item_09", path: "/assets/maps/livingroom/客厅物品_sprites/item_09.png" },
      { key: "item_10", path: "/assets/maps/livingroom/客厅物品_sprites/item_10.png" },
      { key: "item_11", path: "/assets/maps/livingroom/客厅物品_sprites/item_11.png" },
      { key: "item_12", path: "/assets/maps/livingroom/客厅物品_sprites/item_12.png" },
      { key: "item_13", path: "/assets/maps/livingroom/客厅物品_sprites/item_13.png" },
      { key: "item_14", path: "/assets/maps/livingroom/客厅物品_sprites/item_14.png" },
      { key: "item_15", path: "/assets/maps/livingroom/客厅物品_sprites/item_15.png" },
    ],
    width: 1407,
    height: 768,
  },
  bathroom: {
    mapKey: "map_bathroom",
    mapJson: "/assets/maps/bathroom/map.json",
    groundKey: "ground_bathroom",
    groundImage: "/assets/maps/bathroom/卫生间.png",
    defaultSpawn: "spawn_bathroom_door",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/bathroom/物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/bathroom/物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/bathroom/物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/bathroom/物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/bathroom/物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/bathroom/物品_sprites/item_06.png" },
      { key: "item_07", path: "/assets/maps/bathroom/物品_sprites/item_07.png" },
      { key: "item_08", path: "/assets/maps/bathroom/物品_sprites/item_08.png" },
      { key: "item_09", path: "/assets/maps/bathroom/物品_sprites/item_09.png" },
    ],
    width: 640,
    height: 480,
  },
  bedroom: {
    mapKey: "map_bedroom",
    mapJson: "/assets/maps/bedroom/map.json",
    groundKey: "ground_bedroom",
    groundImage: "/assets/maps/bedroom/主角房间.png",
    defaultSpawn: "spawn_bedroom_door",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/bedroom/物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/bedroom/物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/bedroom/物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/bedroom/物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/bedroom/物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/bedroom/物品_sprites/item_06.png" },
      { key: "item_07", path: "/assets/maps/bedroom/物品_sprites/item_07.png" },
      { key: "item_08", path: "/assets/maps/bedroom/物品_sprites/item_08.png" },
      { key: "item_09", path: "/assets/maps/bedroom/物品_sprites/item_09.png" },
      { key: "item_10", path: "/assets/maps/bedroom/物品_sprites/item_10.png" },
      { key: "item_11", path: "/assets/maps/bedroom/物品_sprites/item_11.png" },
      { key: "item_12", path: "/assets/maps/bedroom/物品_sprites/item_12.png" },
      { key: "item_13", path: "/assets/maps/bedroom/物品_sprites/item_13.png" },
      { key: "item_14", path: "/assets/maps/bedroom/物品_sprites/item_14.png" },
      { key: "item_15", path: "/assets/maps/bedroom/物品_sprites/item_15.png" },
      { key: "item_16", path: "/assets/maps/bedroom/物品_sprites/item_16.png" },
    ],
    width: 960,
    height: 640,
  },
  bedroom_parents: {
    mapKey: "map_bedroom_parents",
    mapJson: "/assets/maps/bedroom_parents/map.json",
    groundKey: "ground_bedroom_parents",
    groundImage: "/assets/maps/bedroom_parents/父母房间.png",
    defaultSpawn: "spawn_bedroom_parents_door",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/bedroom_parents/物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/bedroom_parents/物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/bedroom_parents/物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/bedroom_parents/物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/bedroom_parents/物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/bedroom_parents/物品_sprites/item_06.png" },
      { key: "item_07", path: "/assets/maps/bedroom_parents/物品_sprites/item_07.png" },
      { key: "item_08", path: "/assets/maps/bedroom_parents/物品_sprites/item_08.png" },
      { key: "item_09", path: "/assets/maps/bedroom_parents/物品_sprites/item_09.png" },
      { key: "item_10", path: "/assets/maps/bedroom_parents/物品_sprites/item_10.png" },
      { key: "item_11", path: "/assets/maps/bedroom_parents/物品_sprites/item_11.png" },
    ],
    width: 960,
    height: 640,
  },
  kitchen: {
    mapKey: "map_kitchen",
    mapJson: "/assets/maps/kitchen/map.json",
    groundKey: "ground_kitchen",
    groundImage: "/assets/maps/kitchen/厨房.png",
    defaultSpawn: "spawn_kitchen_door",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/kitchen/物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/kitchen/物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/kitchen/物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/kitchen/物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/kitchen/物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/kitchen/物品_sprites/item_06.png" },
    ],
    width: 960,
    height: 640,
  },

  // ═══════════════════════════════════════════
  // 学校区域场景
  // ═══════════════════════════════════════════
  classroom: {
    mapKey: "map_classroom",
    mapJson: "/assets/maps/classroom/map.json",
    groundKey: "ground_classroom",
    groundImage: "/assets/maps/classroom/教室.png",
    defaultSpawn: "spawn_classroom_door",
    width: 1280,
    height: 768,
  },
  classroom_3: {
    mapKey: "map_classroom_3",
    mapJson: "/assets/maps/classroom_3/map.json",
    groundKey: "ground_classroom_3",
    groundImage: "/assets/maps/classroom_3/3班教室.png",
    defaultSpawn: "spawn_classroom_3_door",
    width: 1280,
    height: 768,
  },
  corridor: {
    mapKey: "map_corridor",
    mapJson: "/assets/maps/corridor/map.json",
    groundKey: "ground_corridor",
    groundImage: "/assets/maps/corridor/走廊.png",
    defaultSpawn: "spawn_corridor_classroom",
    width: 3200,
    height: 640,
  },
  rooftop: {
    mapKey: "map_rooftop",
    mapJson: "/assets/maps/rooftop/map.json",
    groundKey: "ground_rooftop",
    groundImage: "/assets/maps/rooftop/天台.png",
    defaultSpawn: "spawn_rooftop_door",
    width: 1600,
    height: 960,
  },
  wang_gallery: {
    mapKey: "map_wang_gallery",
    mapJson: "/assets/maps/wang_gallery/map.json",
    groundKey: "ground_wang_gallery",
    groundImage: "/assets/maps/wang_gallery/王老师画廊.png",
    defaultSpawn: "spawn_gallery_door",
    width: 1280,
    height: 640,
  },
  waiting_area: {
    mapKey: "map_waiting_area",
    mapJson: "/assets/maps/waiting_area/map.json",
    groundKey: "ground_waiting_area",
    groundImage: "/assets/maps/waiting_area/候场区.png",
    defaultSpawn: "spawn_waiting_area_center",
    width: 1407,
    height: 768,
  },
};
