import type { MapEntry } from "../types/gameMap";

export const MapRegistry: Record<string, MapEntry> = {
  livingroom: {
    mapKey: "map_livingroom",
    mapJson: "/assets/maps/livingroom/map.json",
    groundKey: "ground_livingroom",
    groundImage: "/assets/maps/livingroom/客厅.png",
    tilesetKey: "tileset_livingroom",
    tilesetImage: "/assets/maps/livingroom/tileset.png",
    tilesetNameInTiled: "dummy",
    defaultSpawn: "spawn_livingroom_center",
    furnitureImages: [
      { key: "item_01", path: "/assets/maps/livingroom/客厅物品_sprites/item_01.png" },
      { key: "item_02", path: "/assets/maps/livingroom/客厅物品_sprites/item_02.png" },
      { key: "item_03", path: "/assets/maps/livingroom/客厅物品_sprites/item_03.png" },
      { key: "item_04", path: "/assets/maps/livingroom/客厅物品_sprites/item_04.png" },
      { key: "item_05", path: "/assets/maps/livingroom/客厅物品_sprites/item_05.png" },
      { key: "item_06", path: "/assets/maps/livingroom/客厅物品_sprites/item_06.png" },
      { key: "item_06_flip", path: "/assets/maps/livingroom/客厅物品_sprites/item_06_flip.png" },
      { key: "item_07", path: "/assets/maps/livingroom/客厅物品_sprites/item_07.png" },
      { key: "item_08", path: "/assets/maps/livingroom/客厅物品_sprites/item_08.png" },
      { key: "item_09", path: "/assets/maps/livingroom/客厅物品_sprites/item_09.png" },
      { key: "item_10", path: "/assets/maps/livingroom/客厅物品_sprites/item_10.png" },
      { key: "item_11", path: "/assets/maps/livingroom/客厅物品_sprites/item_11.png" },
      { key: "item_12", path: "/assets/maps/livingroom/客厅物品_sprites/item_12.png" },
      { key: "item_13", path: "/assets/maps/livingroom/客厅物品_sprites/item_13.png" },
      { key: "item_14", path: "/assets/maps/livingroom/客厅物品_sprites/item_14.png" },
      { key: "item_15", path: "/assets/maps/livingroom/客厅物品_sprites/item_15.png" },
    ],
    width: 1692,
    height: 929,
    tileWidth: 32,
    tileHeight: 32,
  },
  bathroom: {
    mapKey: "map_bathroom",
    mapJson: "/assets/maps/bathroom/map.json",
    groundKey: "ground_bathroom",
    groundImage: "/assets/maps/bathroom/卫生间.png",
    tilesetKey: "tileset_bathroom",
    tilesetImage: "/assets/maps/bathroom/tileset.png",
    tilesetNameInTiled: "dummy",
    defaultSpawn: "spawn_bathroom_door",
    width: 640,
    height: 480,
    tileWidth: 32,
    tileHeight: 32,
  },
  bedroom: {
    mapKey: "map_bedroom",
    mapJson: "/assets/maps/bedroom/map.json",
    groundKey: "ground_bedroom",
    groundImage: "/assets/maps/bedroom/主角房间.png",
    tilesetKey: "tileset_bedroom",
    tilesetImage: "/assets/maps/bedroom/tileset.png",
    tilesetNameInTiled: "dummy",
    defaultSpawn: "spawn_bedroom_door",
    width: 960,
    height: 640,
    tileWidth: 32,
    tileHeight: 32,
  },
  bedroom_parents: {
    mapKey: "map_bedroom_parents",
    mapJson: "/assets/maps/bedroom_parents/map.json",
    groundKey: "ground_bedroom_parents",
    groundImage: "/assets/maps/bedroom_parents/父母房间.png",
    tilesetKey: "tileset_bedroom_parents",
    tilesetImage: "/assets/maps/bedroom_parents/tileset.png",
    tilesetNameInTiled: "dummy",
    defaultSpawn: "spawn_bedroom_parents_door",
    width: 960,
    height: 640,
    tileWidth: 32,
    tileHeight: 32,
  },
  kitchen: {
    mapKey: "map_kitchen",
    mapJson: "/assets/maps/kitchen/map.json",
    groundKey: "ground_kitchen",
    groundImage: "/assets/maps/kitchen/厨房.png",
    tilesetKey: "tileset_kitchen",
    tilesetImage: "/assets/maps/kitchen/tileset.png",
    tilesetNameInTiled: "dummy",
    defaultSpawn: "spawn_kitchen_door",
    width: 960,
    height: 640,
    tileWidth: 32,
    tileHeight: 32,
  },
};
